# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ChemistryTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChemistryTab(object):
    def setupUi(self, ChemistryTab):
        ChemistryTab.setObjectName("ChemistryTab")
        # ChemistryTab.resize(1000, 400)
        self.gridLayoutWidget = QtWidgets.QWidget(ChemistryTab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1160, 700))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.search_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.search_btn.setObjectName("search_btn")
        self.gridLayout.addWidget(self.search_btn, 0, 4, 1, 1)
        self.result_area = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.result_area.setReadOnly(True)
        self.result_area.setObjectName("result_area")
        self.gridLayout.addWidget(self.result_area, 3, 2, 1, 1)
        self.label_search_elem = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_search_elem.setFont(font)
        self.label_search_elem.setObjectName("label_search_elem")
        self.gridLayout.addWidget(self.label_search_elem, 0, 1, 1, 1)
        self.symbol_result_area = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.symbol_result_area.setBaseSize(QtCore.QSize(200, 200))
        self.symbol_result_area.setReadOnly(True)
        self.symbol_result_area.setObjectName("symbol_result_area")
        self.gridLayout.addWidget(self.symbol_result_area, 1, 2, 1, 1)
        self.element_search = QtWidgets.QLineEdit(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.element_search.setFont(font)
        self.element_search.setToolTipDuration(-6)
        self.element_search.setObjectName("element_search")
        self.gridLayout.addWidget(self.element_search, 0, 2, 1, 1)
        self.formula_input = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.formula_input.setObjectName("formula_input")
        self.gridLayout.addWidget(self.formula_input, 2, 2, 1, 1)
        self.calculate_btn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.calculate_btn.setObjectName("calculate_btn")
        self.gridLayout.addWidget(self.calculate_btn, 2, 4, 1, 1)
        self.label_calc_chem = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_calc_chem.setObjectName("label_calc_chem")
        self.gridLayout.addWidget(self.label_calc_chem, 2, 1, 1, 1)

        self.retranslateUi(ChemistryTab)
        QtCore.QMetaObject.connectSlotsByName(ChemistryTab)

    def retranslateUi(self, ChemistryTab):
        _translate = QtCore.QCoreApplication.translate
        ChemistryTab.setWindowTitle(_translate("ChemistryTab", "Form"))
        self.search_btn.setText(_translate("ChemistryTab", "Найти символ"))
        self.label_search_elem.setText(_translate("ChemistryTab", "Поиск элемента:"))
        self.element_search.setPlaceholderText(_translate("ChemistryTab", "Введите название (водород, железо))"))
        self.formula_input.setPlaceholderText(_translate("ChemistryTab", "Введите формулу (H2SO4)"))
        self.calculate_btn.setText(_translate("ChemistryTab", "Рассчитать"))
        self.label_calc_chem.setText(_translate("ChemistryTab", "Расчет формулы:"))
