# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PeriodicTableTab.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PeriodicTab(object):
    def setupUi(self, PeriodicTab):
        PeriodicTab.setObjectName("PeriodicTab")
        PeriodicTab.resize(1160, 700)
        self.verticalLayoutWidget = QtWidgets.QWidget(PeriodicTab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 1141, 681))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.periodic_table = QtWidgets.QTableWidget(self.verticalLayoutWidget)
        self.periodic_table.setRowCount(9)
        self.periodic_table.setColumnCount(18)
        self.periodic_table.setObjectName("periodic_table")
        self.periodic_table.horizontalHeader().setDefaultSectionSize(62)
        self.periodic_table.horizontalHeader().setMinimumSectionSize(40)
        self.verticalLayout.addWidget(self.periodic_table)

        self.retranslateUi(PeriodicTab)
        QtCore.QMetaObject.connectSlotsByName(PeriodicTab)

    def retranslateUi(self, PeriodicTab):
        _translate = QtCore.QCoreApplication.translate
        PeriodicTab.setWindowTitle(_translate("PeriodicTab", "Form"))
